### ISSUE TITLE
Missing output dir for tsconfig and missing env file.

### ISSUE THREAD

**Issue by QuantumInformation** [googlesamples/functions-as-a-service#2]
I think you are missing an output dir in the ts config? I can't find the dir gcf and I don't see any tests

Also If I run deploy from master
```
➜  functions-as-a-service git:(829af1f) sh deploy.sh 
ERROR: (gcloud) Failed to load YAML from [.env.yaml]: Unable to read file [.env.yaml]: [Errno 2] No such file or directory: '.env.yaml'
```
Kind regards

**Comment by QuantumInformation** [comment]
Also missing the deploy script in the gcf folder which I wanting to reference.

**Comment by grant** [comment]
- I fixed the directions to say `.env.yaml`. We already have an example file.
- There is no output dir, it is optional in TS. We just transpile in the same directory as our source `ts` files.
