### ISSUE TITLE
[question] Access-Control-Allow-Origin position

### ISSUE THREAD

**Issue by QuantumInformation** [googlesamples/functions-as-a-service#3]
I was wondering why you set the Access-Control-Allow-Origin header at the end of the function vs the start?

https://github.com/googlesamples/functions-as-a-service/blob/master/index.ts#L27

Granted the options request won't have paths, but it could be more obvious if the headers were set at the top?

**Comment by grant** [comment]
It does not matter.

It was just put there since all the `res` object build-up is there rather than scattered in the code.
